version: "2"

linters:
  enable:
    - loglinter

  settings:
    custom:
      loglinter:
        path: ./logLinter.so
        description: "Check logs"
        original-url: github.com/Fista6k/logLinter