version: "2"

linters:
  enable:
    - loglinter
  settings:
    custom:
      loglinter:
        path: ./cmd/logLinter/logLinter.exe
        description: "Check logs"
        original-url: github.com/Fista6k/logLinter